# This is a basic workflow to help you get started with Actions

name: CI
#needs: build-and-test

# Controls when the workflow will run dd
on: 
  push: 
    
jobs:
  build-and-test:
    strategy:
      matrix:
        os: ["windows-2022", "macos-12"]

      fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
     
      - name: test  matrix windows
        if: ${{matrix.os}} == 'windows-2022'
        shell: bash 
        run: > 
          echo "WINDOWS" &&
          ls

      - name: test  matrix ubuntu
        if: ${{matrix.os}} == 'ubuntu'
        shell: bash 
        run: > 
          echo "ubuntu" &&
          ls

      - name: test  matrix mac
        if: ${{matrix.os}} == 'macos-12'
        shell: bash 
        run: > 
          echo "mac" &&
          ls