# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare env
        run: sudo apt-get install cmake gcc -y git
      - name: Generate Changelog
        run: echo "change log from git  !todo " > ${{ github.workspace }}-CHANGELOG.txt


      - name: compile
        run: > 
              mkdir -p bin &&
              chmod +x build_and_run.sh &&
               ./build_and_run.sh 

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: bin/*
          
          