# This is a basic workflow to help you get started with Actions

name: CI
#needs: build-and-test

# Controls when the workflow will run dd
on: 
  push: 
    
jobs:
  build-and-test:
    strategy:
      matrix:
        os: ["windows-2022", "macos-12"]

      fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
     
      - name: test  matrix windows
        if: ${{matrix.os}}  ="windows"
        run: > 
          echo "WINDOWS"

      - name: test  matrix ubuntu
        if: ${{matrix.os}}  ="ubuntu"
        run: > 
          echo "ubuntu"

      - name: test  matrix mac
        if: ${{matrix.os}}  ="mac"
        run: > 
          echo "mac"

      - name: tst
        run: >
          cd bin/
          ls -al 
